version: 2
jobs:
  build:
    working_directory:
      /go/src/github.com/qlikmats/server-side-extension/examples/go/basic_example
    docker:
      - image: grpc/go
    steps:
      - checkout
      - run:
          name: Copy code to Go workspace
          command:
            cp -R examples/go/basic_example/*
            /go/src/github.com/qlikmats/server-side-extension/examples/go/basic_example
      - run :
          name: Generate protobuf/gRPC code.
          command: protoc -I ./proto ./proto/ServerSideExtension.proto --go_out=plugins=grpc:/go/src/github.com/qlikmats/server-side-extension/examples/go/basic_example/gen            
      - run:
          name: Go get dependencies
          command: go get -t -d -v ./...
      - run:
          name: Start SSE Server/Plugin
          command: go run ./server.go
          background: true
      - run:
          name: Sleep 2s
          command: sleep 2
      - run:
          name: Run tests
          command: go test -v test/sseplugin_test.go

